PYTORCH_ENABLE_MPS_FALLBACK: "1"
PYTORCH_MPS_HIGH_WATERMARK_RATIO: "0.0"
VAE_FILENAMES:
  - filename: xlvaeapp.pth
    url: https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth
  - filename: vaeapp_sd15.pth
    url: https://huggingface.co/lllyasviel/misc/resolve/main/vaeapp_sd15.pt
  - filename: xl-to-v1_interposer-v4.0.safetensors
    url: https://huggingface.co/mashb1t/misc/resolve/main/xl-to-v1_interposer-v4.0.safetensors
DEFAULT_ARGS:
  share: false
  preset: "realistic"
  disable_preset_selection: false
  language: "default"
  disable_offload_from_vram: false
  theme: null
  disable_image_log: false
  disable_analytics: true
  disable_metadata: false
  disable_preset_download: false
  disable_enhance_output_sorting: false
  enable_auto_describe_image: false
  always_download_new_model: false
  rebuild_hash_cache: null
  always_offload_from_vram: true
  disable_cuda_malloc: true
  in_browser: true
  port: null
