from orderedattrdict import AttrDict

TASK_PARAMS = AttrDict({
    "args": [
        False,
        "Remove the clock from the wall",
        "unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label",
        ["Fooocus V2", "Fooocus Photograph", "Fooocus Negative"],
        "Speed",
        '896×1152 <span style="color: grey;"> ∣ 7:9</span>',
        1,
        "png",
        "5469139041649198568",
        False,
        2,
        3,
        "realisticStockPhoto_v20.safetensors",
        "None",
        0.5,
        True,
        "SDXL_FILM_PHOTOGRAPHY_STYLE_V1.safetensors",
        0.25,
        True,
        "None",
        1,
        True,
        "None",
        1,
        True,
        "None",
        1,
        True,
        "None",
        1,
        True,
        "inpaint",
        "Disabled",
        None,
        [],
        {"image": "array of np.uint8", "mask": "array of np.uint8"},
        "",
        None,
        False,
        False,
        False,
        False,
        1.5,
        0.8,
        0.3,
        7,
        2,
        "dpmpp_2m_sde_gpu",
        "karras",
        "Default (model)",
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        False,
        False,
        False,
        False,
        64,
        128,
        "joint",
        0.25,
        False,
        1.01,
        1.02,
        0.99,
        0.95,
        False,
        False,
        "v2.6",
        1,
        0.618,
        False,
        False,
        0,
        False,
        False,
        "fooocus",
        None,
        0.5,
        0.6,
        "ImagePrompt",
        None,
        0.5,
        0.6,
        "ImagePrompt",
        None,
        0.5,
        0.6,
        "ImagePrompt",
        None,
        0.5,
        0.6,
        "ImagePrompt",
        False,
        0,
        False,
        None,
        False,
        "Disabled",
        "Before First Enhancement",
        "Original Prompts",
        False,
        "",
        "",
        "",
        "sam",
        "full",
        "vit_b",
        0.25,
        0.3,
        0,
        False,
        "v2.6",
        1,
        0.618,
        0,
        False,
        False,
        "",
        "",
        "",
        "sam",
        "full",
        "vit_b",
        0.25,
        0.3,
        0,
        False,
        "v2.6",
        1,
        0.618,
        0,
        False,
        False,
        "",
        "",
        "",
        "sam",
        "full",
        "vit_b",
        0.25,
        0.3,
        0,
        False,
        "v2.6",
        1,
        0.618,
        0,
        False,
    ],
    "yields": [],
    "results": [],
    "last_stop": False,
    "processing": False,
    "performance_loras": [],
    "generate_image_grid": False,
    "prompt": "Remove the clock from the wall",
    "negative_prompt": "unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label",
    "style_selections": ["Fooocus V2", "Fooocus Photograph", "Fooocus Negative"],
    "performance_selection": "enum modules.flags.Performance.SPEED",
    "steps": 30,
    "original_steps": 30,
    "aspect_ratios_selection": '896×1152 <span style="color: grey;"> ∣ 7:9</span>',
    "image_number": 1,
    "output_format": "png",
    "seed": 5469139041649198568,
    "read_wildcards_in_order": False,
    "sharpness": 2,
    "cfg_scale": 3,
    "base_model_name": "realisticStockPhoto_v20.safetensors",
    "refiner_model_name": "None",
    "refiner_switch": 0.5,
    "loras": [("SDXL_FILM_PHOTOGRAPHY_STYLE_V1.safetensors", 0.25)],
    "input_image_checkbox": True,
    "current_tab": "inpaint",
    "uov_method": "Disabled",
    "uov_input_image": None,
    "outpaint_selections": [],
    "inpaint_input_image": {"image": "array of np.uint8", "mask": "array of np.uint8"},
    "inpaint_additional_prompt": "",
    "inpaint_mask_image_upload": None,
    "disable_preview": False,
    "disable_intermediate_results": False,
    "disable_seed_increment": False,
    "black_out_nsfw": False,
    "adm_scaler_positive": 1.5,
    "adm_scaler_negative": 0.8,
    "adm_scaler_end": 0.3,
    "adaptive_cfg": 7,
    "clip_skip": 2,
    "sampler_name": "dpmpp_2m_sde_gpu",
    "scheduler_name": "karras",
    "vae_name": "Default (model)",
    "overwrite_step": -1,
    "overwrite_switch": -1,
    "overwrite_width": -1,
    "overwrite_height": -1,
    "overwrite_vary_strength": -1,
    "overwrite_upscale_strength": -1,
    "mixing_image_prompt_and_vary_upscale": False,
    "mixing_image_prompt_and_inpaint": False,
    "debugging_cn_preprocessor": False,
    "skipping_cn_preprocessor": False,
    "canny_low_threshold": 64,
    "canny_high_threshold": 128,
    "refiner_swap_method": "joint",
    "controlnet_softness": 0.25,
    "freeu_enabled": False,
    "freeu_b1": 1.01,
    "freeu_b2": 1.02,
    "freeu_s1": 0.99,
    "freeu_s2": 0.95,
    "debugging_inpaint_preprocessor": False,
    "inpaint_disable_initial_latent": False,
    "inpaint_engine": "v2.6",
    "inpaint_strength": 1,
    "inpaint_respective_field": 0.618,
    "inpaint_advanced_masking_checkbox": False,
    "invert_mask_checkbox": False,
    "inpaint_erode_or_dilate": 0,
    "save_final_enhanced_image_only": False,
    "save_metadata_to_images": False,
    "metadata_scheme": "metadata <MetadataScheme.FOOOCUS: 'fooocus'>",
    "cn_tasks": {"ImagePrompt": [], "PyraCanny": [], "CPDS": [], "FaceSwap": []},
    "debugging_dino": False,
    "dino_erode_or_dilate": 0,
    "debugging_enhance_masks_checkbox": False,
    "enhance_input_image": None,
    "enhance_checkbox": False,
    "enhance_uov_method": "Disabled",
    "enhance_uov_processing_order": "Before First Enhancement",
    "enhance_uov_prompt_type": "Original Prompts",
    "enhance_ctrls": [],
    "should_enhance": False,
    "images_to_enhance_count": 0,
    "enhance_stats": {},
})
